### ISSUE TITLE
Dlaczego nazwa repozytorium ma w sobie kropkę

### ISSUE THREAD

**Issue by phenolophthaleinum** [degustacja/Tab.kalimba#1]
No właśnie dlaczego, przecież to jest pogwałcenie wszystkich zasad

p.s za wielką litere powinna byc banicja

!voteban @degustacja (1/2 votes)

**Comment by AvirFrog** [comment]
@phenolophthaleinum tłumaczyłem oponentce że kropka jest tragicznym pomysłem i duże litery też. 

!voteban @degustacja (2/2 votes)

**Comment by phenolophthaleinum** [comment]
Czyli będzie warn, pierwszy z 3.
Zamykam

**Comment by AvirFrog** [comment]
# OSTRZEŻENIE DLA UŻYTKOWNIKA @degustacja 

Z powodu rażącego naruszenia regulaminu dobrego smaku programowania, na użytkowniczkę @degustacja nałożone zostaje ostrzeżenie na 90 dni.
